
---
spree_option_values_variants:
  columns:
  - variant_id
  - option_value_id
  records: 
  - - 28
    - 8
  - - 28
    - 19
  - - 29
    - 9
  - - 29
    - 19
  - - 30
    - 10
  - - 30
    - 19
  - - 31
    - 11
  - - 31
    - 19
  - - 32
    - 8
  - - 32
    - 20
  - - 33
    - 9
  - - 33
    - 20
  - - 34
    - 10
  - - 34
    - 20
  - - 35
    - 11
  - - 35
    - 20
  - - 37
    - 8
  - - 37
    - 17
  - - 38
    - 8
  - - 39
    - 9
  - - 39
    - 17
  - - 40
    - 9
  - - 41
    - 10
  - - 41
    - 17
  - - 42
    - 10
  - - 43
    - 11
  - - 43
    - 17
  - - 44
    - 11
  - - 46
    - 8
  - - 46
    - 15
  - - 47
    - 8
  - - 47
    - 16
  - - 48
    - 9
  - - 48
    - 15
  - - 49
    - 9
  - - 49
    - 16
  - - 50
    - 10
  - - 50
    - 15
  - - 51
    - 10
  - - 51
    - 16
  - - 52
    - 11
  - - 52
    - 15
  - - 53
    - 11
  - - 53
    - 16
  - - 55
    - 8
  - - 55
    - 21
  - - 56
    - 9
  - - 56
    - 21
  - - 57
    - 10
  - - 57
    - 21
  - - 58
    - 21
  - - 58
    - 22
  - - 60
    - 22
  - - 60
    - 23
  - - 61
    - 8
  - - 61
    - 23
  - - 62
    - 9
  - - 62
    - 23
  - - 63
    - 10
  - - 63
    - 23
  - - 65
    - 15
  - - 65
    - 22
  - - 66
    - 16
  - - 66
    - 22
  - - 67
    - 8
  - - 67
    - 15
  - - 68
    - 8
  - - 68
    - 16
  - - 69
    - 9
  - - 69
    - 15
  - - 70
    - 9
  - - 70
    - 16
  - - 71
    - 10
  - - 71
    - 15
  - - 72
    - 10
  - - 72
    - 16
  - - 74
    - 12
  - - 74
    - 22
  - - 75
    - 13
  - - 75
    - 22
  - - 76
    - 14
  - - 76
    - 22
  - - 77
    - 8
  - - 77
    - 12
  - - 78
    - 8
  - - 78
    - 13
  - - 79
    - 8
  - - 79
    - 14
  - - 80
    - 9
  - - 80
    - 12
  - - 81
    - 9
  - - 81
    - 13
  - - 82
    - 9
  - - 82
    - 14
  - - 83
    - 10
  - - 83
    - 12
  - - 84
    - 10
  - - 84
    - 13
  - - 85
    - 10
  - - 85
    - 14
  - - 87
    - 15
  - - 87
    - 22
  - - 88
    - 8
  - - 88
    - 15
  - - 89
    - 9
  - - 89
    - 15
  - - 90
    - 10
  - - 90
    - 15
  - - 93
    - 22
  - - 93
    - 25
  - - 94
    - 8
  - - 94
    - 25
  - - 95
    - 9
  - - 95
    - 25
  - - 96
    - 10
  - - 96
    - 25
  - - 98
    - 15
  - - 98
    - 22
  - - 99
    - 22
  - - 100
    - 8
  - - 100
    - 15
  - - 101
    - 8
  - - 102
    - 9
  - - 102
    - 15
  - - 103
    - 9
  - - 104
    - 10
  - - 104
    - 15
  - - 105
    - 10
  - - 111
    - 22
  - - 111
    - 23
  - - 112
    - 8
  - - 112
    - 23
  - - 113
    - 9
  - - 113
    - 23
  - - 114
    - 10
  - - 114
    - 23
  - - 116
    - 22
  - - 116
    - 26
  - - 117
    - 22
  - - 117
    - 27
  - - 118
    - 8
  - - 118
    - 26
  - - 119
    - 8
  - - 119
    - 27
  - - 120
    - 9
  - - 120
    - 26
  - - 121
    - 9
  - - 121
    - 27
  - - 122
    - 10
  - - 122
    - 26
  - - 123
    - 10
  - - 123
    - 27
  - - 125
    - 22
  - - 125
    - 28
  - - 126
    - 8
  - - 126
    - 28
  - - 127
    - 9
  - - 127
    - 28
  - - 128
    - 10
  - - 128
    - 28
  - - 129
    - 11
  - - 129
    - 28
  - - 131
    - 15
  - - 131
    - 22
  - - 132
    - 8
  - - 132
    - 15
  - - 133
    - 9
  - - 133
    - 15
  - - 134
    - 10
  - - 134
    - 15
  - - 135
    - 11
  - - 135
    - 15
  - - 137
    - 15
  - - 137
    - 22
  - - 138
    - 8
  - - 138
    - 15
  - - 139
    - 9
  - - 139
    - 15
  - - 140
    - 10
  - - 140
    - 15
  - - 141
    - 11
  - - 141
    - 15
  - - 143
    - 15
  - - 143
    - 22
  - - 144
    - 8
  - - 144
    - 15
  - - 145
    - 9
  - - 145
    - 15
  - - 146
    - 10
  - - 146
    - 15
  - - 147
    - 11
  - - 147
    - 15
  - - 149
    - 15
  - - 149
    - 22
  - - 150
    - 22
  - - 150
    - 26
  - - 151
    - 8
  - - 151
    - 15
  - - 152
    - 8
  - - 152
    - 26
  - - 153
    - 9
  - - 153
    - 15
  - - 154
    - 9
  - - 154
    - 26
  - - 155
    - 10
  - - 155
    - 15
  - - 156
    - 10
  - - 156
    - 26
  - - 157
    - 11
  - - 157
    - 15
  - - 158
    - 11
  - - 158
    - 26
  - - 160
    - 22
  - - 160
    - 91
  - - 161
    - 8
  - - 161
    - 91
  - - 162
    - 9
  - - 162
    - 91
  - - 163
    - 10
  - - 163
    - 91
  - - 165
    - 15
  - - 165
    - 22
  - - 166
    - 22
  - - 166
    - 35
  - - 167
    - 8
  - - 167
    - 15
  - - 168
    - 8
  - - 168
    - 35
  - - 169
    - 9
  - - 169
    - 15
  - - 170
    - 9
  - - 170
    - 35
  - - 171
    - 10
  - - 171
    - 15
  - - 172
    - 10
  - - 172
    - 35
  - - 174
    - 22
  - - 174
    - 94
  - - 175
    - 8
  - - 175
    - 94
  - - 176
    - 9
  - - 176
    - 94
  - - 177
    - 10
  - - 177
    - 94
  - - 179
    - 15
  - - 179
    - 22
  - - 180
    - 22
  - - 180
    - 26
  - - 181
    - 8
  - - 181
    - 15
  - - 182
    - 8
  - - 182
    - 26
  - - 183
    - 9
  - - 183
    - 15
  - - 184
    - 9
  - - 184
    - 26
  - - 185
    - 10
  - - 185
    - 15
  - - 186
    - 10
  - - 186
    - 26
  - - 188
    - 22
  - - 188
    - 78
  - - 189
    - 8
  - - 189
    - 78
  - - 190
    - 9
  - - 190
    - 78
  - - 191
    - 10
  - - 191
    - 78
  - - 193
    - 8
  - - 193
    - 24
  - - 194
    - 8
  - - 194
    - 95
  - - 195
    - 9
  - - 195
    - 24
  - - 196
    - 9
  - - 196
    - 95
  - - 197
    - 10
  - - 197
    - 24
  - - 198
    - 10
  - - 198
    - 95
  - - 199
    - 11
  - - 199
    - 24
  - - 200
    - 11
  - - 200
    - 95
  - - 202
    - 11
  - - 202
    - 19
  - - 204
    - 22
  - - 205
    - 8
  - - 206
    - 9
  - - 207
    - 10
  - - 209
    - 22
  - - 209
    - 27
  - - 210
    - 22
  - - 210
    - 40
  - - 211
    - 22
  - - 211
    - 26
  - - 212
    - 22
  - - 212
    - 47
  - - 213
    - 16
  - - 213
    - 22
  - - 214
    - 8
  - - 214
    - 27
  - - 215
    - 8
  - - 215
    - 40
  - - 216
    - 8
  - - 216
    - 26
  - - 217
    - 8
  - - 217
    - 47
  - - 218
    - 8
  - - 218
    - 16
  - - 219
    - 9
  - - 219
    - 27
  - - 220
    - 9
  - - 220
    - 40
  - - 221
    - 9
  - - 221
    - 26
  - - 222
    - 9
  - - 222
    - 47
  - - 223
    - 9
  - - 223
    - 16
  - - 224
    - 10
  - - 224
    - 27
  - - 225
    - 10
  - - 225
    - 40
  - - 226
    - 10
  - - 226
    - 26
  - - 227
    - 10
  - - 227
    - 47
  - - 228
    - 10
  - - 228
    - 16
  - - 230
    - 10
  - - 230
    - 21
  - - 231
    - 11
  - - 231
    - 21
